# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-10-23 00:13
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AporteMes',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('usuario', models.CharField(max_length=100)),
                ('aporte', models.FloatField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='AporteTotal',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('aporte', models.FloatField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='HistorialGastos',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad', models.FloatField(default=0)),
                ('motivo', models.CharField(max_length=10000)),
            ],
        ),
    ]
