# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-10-24 00:37
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AporteDatabase', '0003_auto_20161023_1835'),
    ]

    operations = [
        migrations.CreateModel(
            name='HistorialPagos',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('usuario', models.CharField(max_length=100)),
                ('aporte', models.FloatField(default=0)),
                ('fecha', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
