# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-10-24 01:01
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AporteDatabase', '0004_historialpagos'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='historialpagos',
            name='fecha',
        ),
        migrations.AddField(
            model_name='historialpagos',
            name='ano',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='historialpagos',
            name='mes',
            field=models.IntegerField(default=0),
        ),
    ]
