# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-11-24 02:41
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AporteDatabase', '0006_auto_20161123_1749'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historialpagos',
            name='comentarios',
            field=models.CharField(max_length=1000, null=True),
        ),
    ]
