# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-12-31 22:41
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AporteDatabase', '0007_auto_20161124_0241'),
    ]

    operations = [
        migrations.CreateModel(
            name='Identidad',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_nodo', models.CharField(max_length=100)),
                ('logo_nodo', models.FileField(upload_to='')),
                ('en_uso', models.BooleanField(default=False)),
            ],
        ),
    ]
