# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-12-31 23:11
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AporteDatabase', '0008_identidad'),
    ]

    operations = [
        migrations.AddField(
            model_name='identidad',
            name='hint_rango',
            field=models.CharField(default='', max_length=15),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='identidad',
            name='logo_nodo',
            field=models.FileField(upload_to='media'),
        ),
    ]
