# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-06-11 01:18
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AporteDatabase', '0010_auto_20180101_0240'),
    ]

    operations = [
        migrations.AddField(
            model_name='aportemes',
            name='activo',
            field=models.BooleanField(default=True),
        ),
    ]
