# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-06-16 22:15
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('AporteDatabase', '0011_aportemes_activo'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='aportemes',
            name='activo',
        ),
        migrations.RemoveField(
            model_name='aportemes',
            name='rango',
        ),
    ]
