# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-06-16 22:20
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AporteDatabase', '0012_auto_20190616_1815'),
    ]

    operations = [
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('usuario', models.CharField(max_length=100)),
            ],
        ),
        migrations.DeleteModel(
            name='AporteMes',
        ),
    ]
